; =========================================================
; MAPEO DE EQUIPOS POR UUID HACIA SU RESPECTIVA CONFIG.
; =========================================================
;
; FORMATO:
; UUID=ConfigDeHardware,NombreDeHost
;

; Cuarto de Samuel (nuleado por privacidad).
03D502E0-045E-0000-0000-000000000000=HWConfig1,PC-DE-SAMU

; Dummy para la demo en VMWare.
19774D56-44CE-5B4D-E30D-AA19FCF0C84D=HWConfig3,VMWARE-VM


; =========================================================
; AVISO A NAVEGANTES. "ENABLEDELAYEDEXPANSION" esta acti-
; vado en el script "Colonizador.bat"; cualquier valor
; que contenga "!" o cualquier otro caracter utilizado por
; DELAYEDEXPANSION no aparecerá o romperá el script. Yo
; he avisado.
; =========================================================

; ///////////////////////////////////////////////////////



