:: 
:: IMPORTANTE!!
::
:: UTILIZA LA FUNCIÓN DE "BUSCAR Y REEMPLAZAR" DE "Notepad++" O TU EDITOR FAVORITO, Y:
:: - Reemplaza "smb-interno-so_instred" por la ruta hacia la carpeta compartida SMB. Por ejemplo: "COSAS_INTERNAS\Aceitunas\WIMMANAGER".
:: - Reemplaza "IP.DEL.SERVIDOR.SMB" por la IP del servidor SMB. No tiene mucho misterio.
:: - Reemplaza "USUARIO" por el nombre de usuario del servidor SMB (altamente recomendado: la carpeta compartida debería tener permisos de sólo lectura por seguridad).
:: - Reemplaza "CONTRASEÑA" por... la contraseña del usuario SMB (¿a que no lo has adivinado? vaya humor más malo gasto ngl).
::
:: ...salvo que te vaya el rollo sado. En ese caso, suerte.

@echo off
chcp 65001 >NUL
title Terraformando el hostil entorno de red...

:puntoinicial
mode con: cols=74 lines=6
set /a rompebucles=0
:puntoinicial_contenido
cls
echo.
echo  [^|] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [ ] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [/] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [ ] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [—] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [ ] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [\] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [ ] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
set /a rompebucles=%rompebucles%+1
if %rompebucles% neq 3 goto puntoinicial_contenido


:bucle_ping
set /a rompebucles=0
:bucle_ping_contenido
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [^|] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
ping -n 1 IP.DEL.SERVIDOR.SMB | find "TTL=" >nul
if %errorlevel% equ 0 goto sincronizar_fecha_y_hora
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [/] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [—] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [\] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
ping -n 1 IP.DEL.SERVIDOR.SMB | find "TTL=" >nul
if %errorlevel% equ 0 goto sincronizar_fecha_y_hora
set /a rompebucles=%rompebucles%+1
if %rompebucles% equ 8 goto error_timeout
goto bucle_ping

:sincronizar_fecha_y_hora
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [^|] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [/] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [-] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [ ] Montando la carpeta en red con los activos bajo "A:\"...
net time \\IP.DEL.SERVIDOR.SMB /set /yes
if %errorlevel% equ 0 goto montar_carpeta_smb
goto error_smb_sincronizar_fecha_y_hora

:montar_carpeta_smb
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [^|] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [/] Montando la carpeta en red con los activos bajo "A:\"...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [—] Montando la carpeta en red con los activos bajo "A:\"...
net use A: \\IP.DEL.SERVIDOR.SMB\RUTA_CARPETA_COMPARTIDA_SMB /user:USUARIO "CONTRASEÑA" /persistent:no >nul

if exist A:\colonizador.bat goto confirmacion
goto error_smb_montar_carpeta_smb


:error_timeout
mode con: cols=67 lines=8
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [X] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [^?] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [^?] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Destino inalcanzable. Pulsa una tecla para reiniciar el PC.
pause >nul
wpeutil reboot

:error_smb_sincronizar_fecha_y_hora
mode con: cols=75 lines=8
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [X] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [^?] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> ERROR al sincronizar. Pulsa una tecla para reiniciar el PC.
pause >nul
wpeutil reboot

:error_smb_montar_carpeta_smb
mode con: cols=75 lines=8
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [X] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> ERROR al montar. Pulsa una tecla para reiniciar el PC.
pause >nul
wpeutil reboot


:confirmacion
mode con: cols=75 lines=8
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat)
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat).
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat)..
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat)...
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat)....
timeout /t 1 >nul
cls
echo.
echo  [√] Esperando a que terminen los preparativos de "wpeinit.exe"...
echo  [√] Buscando conexión con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Sincronizando la fecha y hora con el servidor SMB (IP.DEL.SERVIDOR.SMB)...
echo  [√] Montando la carpeta en red con los activos bajo "A:\"...
echo.
echo   ^> Redirigiendo al script principal (A:\colonizador.bat).....

exit