; PC de Samuel - Gigabyte z370 Aorus Gaming 3, ARC A770, i7-8700K, 64 GiB DDR4 3400 CL13
;
; La cabecera o marca de bloque de justo debajo (y entre corchetes) debe coincidir con:
; 1. El valor justo después del UUID en la whitelist.
; 2. El nombre de este archivo de texto justo antes del ".ini".
;
; TODO EL CONTENIDO/ACTIVOS RELACIONADOS CON ESTA CONFIG. DE HARDWARE VAN DENTRO DE UN DIRECTORIO CON EL MISMO NOMBRE.

[HWConfig1]
;--------------------------------------------------------------------------------------------------------------------
; ¡CUIDADO! Creo que el nombre de las variables es bastante autoexplicativo. Piensa en los riesgos:
; Si el equipo ve su orden de arranque alterado, podría iniciar en red y acabar automágicamente
; formateado. Piénsalo bien... y ponle clave al UEFI o BIOS mientras le echas un ojo a la pila de 3.7v.
;
; NOTA: requiere de "omitir_seleccion_manual_de_disco" y "numero_de_disco_preseleccionado".

instalacion_desatendida=0
instalacion_desatendida_reiniciar_automaticamente_al_finalizar=1
numero_de_sistema_preseleccionado=1
numero_de_variante_de_sistema_preseleccionada=1
;--------------------------------------------------------------------------------------------------------------------

;--------------------------------------------------------------------------------------------------------------------
; ¡CUIDADO! Si el orden de los discos cambiase (controlador NVMe listado después de los discos SATA u otros), podría
; ocurrir una hecatombe. Omítela sólo si realmente sabes lo que estás haciendo.
;
omitir_seleccion_manual_de_disco=0
numero_de_disco_preseleccionado=0
;--------------------------------------------------------------------------------------------------------------------

compact=1
ea=1

; Máximo 4 para no hacerlo ilegible a bajas resoluciones
cantidad_de_sistemas_operativos=3


; ////////////////////////////////////////////////////////////////////////
; ////////////////// DATOS DEL PRIMER SISTEMA OPERATIVO //////////////////
; ////////////////////////////////////////////////////////////////////////
sistema1_nombre=Windows 11 Pro for Workstations (23H2)
sistema1_descripcion=(i) Última versión de Windows. Rendimiento terrible, pero lo nuevo manda.

sistema1_archivo_windows=Windows_HD_w11-ProFW-23H2.wim
sistema1_archivo_winre=WinRE.esd
sistema1_archivo_efi=EFI.esd

; Máximo 4 para no hacerlo ilegible a bajas resoluciones. Si la imagen es .wim pero no tiene variantes,
; debes establecerlo en "1· y darle un valor al índice de la "variante 1", y el cual normalmente suele ser "1" también.
sistema1_variantes=1

; --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- ///

sistema1_variante1_nombre=preconfigurada
sistema1_variante1_descripcion=(i) Incluye un pack de aplicaciones listas para funcionar.
sistema1_variante1_script_de_diskpart=solo_formateo_sin_recrear_de_particiones.txt
sistema1_variante1_indice_de_imagen=1
sistema1_variante1_omitir_imagen_efi=0
sistema1_variante1_omitir_imagen_winre=0
sistema1_variante1_omitir_actualizar_bcd=0

; Se pueden extraer ejecutando "bcdedit /enum all /v" sobre el almacén BCD de la imagen EFI:
; la variable "sistema1_variante1_bcd_uuid_windows" corresponde al identificador cuyo campo de "descripción" corresponda a tu versión de Windows;
; la variable "sistema1_variante1_bcd_uuid_hibernacion" corresponde al identificador cuyo campo de "descripción" sea "Windows Resume Application";
; la variable "sistema1_variante1_bcd_uuid_winre" corresponde al identificador cuyo campo de "descripción" sea "Windows Recovery Environment";
; la variable "sistema1_variante1_bcd_uuid_winre_boot-sdi" corresponde al UUID del identificador único de entrada para "Windows Recovery", cuyo
; valor "path" hace referencia a un archivo "boot.sdi" y usualmente está al final de la salida del comando "bcdedit /enum all".
sistema1_variante1_bcd_uuid_windows=30af8d3d-472d-11f0-a2e6-ba4d9717f5ae
sistema1_variante1_bcd_descripcion_windows=Windows 11
sistema1_variante1_bcd_uuid_hibernacion=30af8d3c-472d-11f0-a2e6-ba4d9717f5ae
sistema1_variante1_bcd_uuid_winre=e85c5247-4724-11f0-b2be-ff92e22e6019
sistema1_variante1_bcd_uuid_winre_boot-sdi=e85c5248-4724-11f0-b2be-ff92e22e6019

sistema1_variante1_inyectar_nombre_de_host=1

; Si quieres inyectar un unattend.xml, este es el sitio indicado. Se buscará dentro de la carpeta con el nombre de esta entrada de
; configuración (eso que está arriba entre corchetes), y evidentemente con el nombre que especifiques.
sistema1_variante1_inyectar_unattend-xml=0
sistema1_variante1_inyectar_unattend-xml_nombre_real=

; Si el equipo tiene un BIOS AMI y quieres inyectar una configuración / perfil de UEFI mediante SCEWIN, este es tu sitio.
; Decir que, aunque ya debes saber esto, meter un conjunto de variables en la NVRAM de "X" versión de ROM en un equipo ejecutando
; "Y" versión siempre sale mal. Los archivos van dentro de "
sistema1_variante1_inyectar_ajustes_de_UEFI=0
sistema1_variante1_inyectar_ajustes_de_UEFI_nombre_real_de_nvram-txt=


; ////////////////////////////////////////////////////////////////////////
; ////////////////// DATOS DEL SEGUNDO SISTEMA OPERATIVO //////////////////
; ////////////////////////////////////////////////////////////////////////
sistema2_nombre=Windows 11 Pro for Workstations (25H2, Sandbox)
sistema2_descripcion=(i) Última versión de Windows. Rendimiento terrible, pero lo nuevo manda.

sistema2_archivo_windows=Windows_HD-w11_ProFW_25H2_S.esd
sistema2_archivo_winre=WinRE.esd
sistema2_archivo_efi=EFI.esd

; Máximo 4 para no hacerlo ilegible a bajas resoluciones. Si la imagen es .wim pero no tiene variantes,
; debes establecerlo en "1· y darle un valor al índice de la "variante 1", y el cual normalmente suele ser "1" también.
sistema2_variantes=1

; --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- ///

sistema2_variante1_nombre=preconfigurada
sistema2_variante1_descripcion=(i) Estado cuasi-limpio con formateo destructivo/completo.
sistema2_variante1_script_de_diskpart=formateo_completo_hdd.txt
sistema2_variante1_indice_de_imagen=1
sistema2_variante1_omitir_imagen_efi=0
sistema2_variante1_omitir_imagen_winre=0
sistema2_variante1_omitir_actualizar_bcd=0

; Se pueden extraer ejecutando "bcdedit /enum all /v" sobre el almacén BCD de la imagen EFI:
; la variable "sistema2_variante1_bcd_uuid_windows" corresponde al identificador cuyo campo de "descripción" corresponda a tu versión de Windows;
; la variable "sistema2_variante1_bcd_uuid_hibernacion" corresponde al identificador cuyo campo de "descripción" sea "Windows Resume Application";
; la variable "sistema2_variante1_bcd_uuid_winre" corresponde al identificador cuyo campo de "descripción" sea "Windows Recovery Environment";
; la variable "sistema2_variante1_bcd_uuid_winre_boot-sdi" corresponde al UUID del identificador único de entrada para "Windows Recovery", cuyo
; valor "path" hace referencia a un archivo "boot.sdi" y usualmente está al final de la salida del comando "bcdedit /enum all".
sistema2_variante1_bcd_uuid_windows=30af8d3d-472d-11f0-a2e6-ba4d9717f5ae
sistema2_variante1_bcd_descripcion_windows=Windows 11
sistema2_variante1_bcd_uuid_hibernacion=30af8d3c-472d-11f0-a2e6-ba4d9717f5ae
sistema2_variante1_bcd_uuid_winre=e85c5247-4724-11f0-b2be-ff92e22e6019
sistema2_variante1_bcd_uuid_winre_boot-sdi=e85c5248-4724-11f0-b2be-ff92e22e6019

sistema2_variante1_inyectar_nombre_de_host=1

; Si quieres inyectar un unattend.xml, este es el sitio indicado. Se buscará dentro de la carpeta con el nombre de esta entrada de
; configuración (eso que está arriba entre corchetes), y evidentemente con el nombre que especifiques.
sistema2_variante1_inyectar_unattend-xml=0
sistema2_variante1_inyectar_unattend-xml_nombre_real=

; Si el equipo tiene un BIOS AMI y quieres inyectar una configuración / perfil de UEFI mediante SCEWIN, este es tu sitio.
; Decir que, aunque ya debes saber esto, meter un conjunto de variables en la NVRAM de "X" versión de ROM en un equipo ejecutando
; "Y" versión siempre sale mal. Los archivos van dentro de "
sistema2_variante1_inyectar_ajustes_de_UEFI=
sistema2_variante1_inyectar_ajustes_de_UEFI_nombre_real_de_nvram-txt=


; ////////////////////////////////////////////////////////////////////////
; ///////////////// DATOS DEL TERCER SISTEMA OPERATIVO //////////////////
; ////////////////////////////////////////////////////////////////////////
sistema3_nombre=Windows Server 2016 Datacenter
sistema3_descripcion=(i) Funciones a tutiplén. Robustez por doquier. Ligereza sin igual.

; Indica si el archivo de imagen usa comprensión estandar y tiene varios índices, o bien sólo tiene un índice y usa comprensión sólida.
; En caso de estar establecido en 1 (archivo .esd), se invocará DISM sin el parámetro "/Index" o "/Name". Aún así, deberá configurarse
; la primera variante del SO (a excepción de "sistema2_variante1_indice_de_imagen"), en especial "sistema2_variante1_script_de_diskpart".

sistema3_archivo_windows=Windows_HD_w2k16-dc.wim
sistema3_archivo_winre=WinRE.esd
sistema3_archivo_efi=EFI.esd

; Máximo 4 para no hacerlo ilegible a bajas resoluciones. Si la imagen es .wim pero no tiene variantes,
; debes establecerlo en "1· y darle un valor al índice de la "variante 1", y el cual normalmente suele ser "1" también.
sistema3_variantes=2

; --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- ///

sistema3_variante1_nombre=limpia
sistema3_variante1_descripcion=(i) Sólo drivers y configuración muy básica.
sistema3_variante1_script_de_diskpart=formateo_completo.txt
sistema3_variante1_indice_de_imagen=1
sistema3_variante1_omitir_imagen_efi=0
sistema3_variante1_omitir_imagen_winre=0
sistema3_variante1_omitir_actualizar_bcd=0

; Se pueden extraer ejecutando "bcdedit /enum all /v" sobre el almacén BCD de la imagen EFI:
; la variable "sistema3_variante1_bcd_uuid_windows" corresponde al identificador cuyo campo de "descripción" corresponda a tu versión de Windows;
; la variable "sistema3_variante1_bcd_uuid_hibernacion" corresponde al identificador cuyo campo de "descripción" sea "Windows Resume Application";
; la variable "sistema3_variante1_bcd_uuid_winre" corresponde al identificador cuyo campo de "descripción" sea "Windows Recovery Environment";
; la variable "sistema3_variante1_bcd_uuid_winre_boot-sdi" corresponde al UUID del identificador único de entrada para "Windows Recovery", cuyo
; valor "path" hace referencia a un archivo "boot.sdi" y usualmente está al final de la salida del comando "bcdedit /enum all".
sistema3_variante1_bcd_uuid_windows=30af8d3d-472d-11f0-a2e6-ba4d9717f5ae
sistema3_variante1_bcd_descripcion_windows=Windows Server 2016 Datacenter
sistema3_variante1_bcd_uuid_hibernacion=30af8d3c-472d-11f0-a2e6-ba4d9717f5ae
sistema3_variante1_bcd_uuid_winre=e85c5247-4724-11f0-b2be-ff92e22e6019
sistema3_variante1_bcd_uuid_winre_boot-sdi=e85c5248-4724-11f0-b2be-ff92e22e6019

sistema3_variante1_inyectar_nombre_de_host=1

; Si quieres inyectar un unattend.xml, este es el sitio indicado. Se buscará dentro de la carpeta con el nombre de esta entrada de
; configuración (eso que está arriba entre corchetes), y evidentemente con el nombre que especifiques.
sistema3_variante1_inyectar_unattend-xml=0
sistema3_variante1_inyectar_unattend-xml_nombre_real=

; Si el equipo tiene un BIOS AMI y quieres inyectar una configuración / perfil de UEFI mediante SCEWIN, este es tu sitio.
; Decir que, aunque ya debes saber esto, meter un conjunto de variables en la NVRAM de "X" versión de ROM en un equipo ejecutando
; "Y" versión siempre sale mal. Los archivos van dentro de "
sistema3_variante1_inyectar_ajustes_de_UEFI=1
sistema3_variante1_inyectar_ajustes_de_UEFI_nombre_real_de_nvram-txt=nvram_f15c_sis3.txt

; --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- /// --- ///

sistema3_variante2_nombre=preconfigurada
sistema3_variante2_descripcion=(i) Incl. un pack de apps listas para funcionar. Formateo destructivo.
sistema3_variante2_script_de_diskpart=formateo_completo.txt
sistema3_variante2_indice_de_imagen=2
sistema3_variante2_omitir_imagen_efi=0
sistema3_variante2_omitir_imagen_winre=0
sistema3_variante2_omitir_actualizar_bcd=0

; Se pueden extraer ejecutando "bcdedit /enum all /v" sobre el almacén BCD de la imagen EFI:
; la variable "sistema3_variante2_bcd_uuid_windows" corresponde al identificador cuyo campo de "descripción" corresponda a tu versión de Windows;
; la variable "sistema3_variante2_bcd_uuid_hibernacion" corresponde al identificador cuyo campo de "descripción" sea "Windows Resume Application";
; la variable "sistema3_variante2_bcd_uuid_winre" corresponde al identificador cuyo campo de "descripción" sea "Windows Recovery Environment";
; la variable "sistema3_variante2_bcd_uuid_winre_boot-sdi" corresponde al UUID del identificador único de entrada para "Windows Recovery", cuyo
; valor "path" hace referencia a un archivo "boot.sdi" y usualmente está al final de la salida del comando "bcdedit /enum all".
sistema3_variante2_bcd_uuid_windows=30af8d3d-472d-11f0-a2e6-ba4d9717f5ae
sistema3_variante2_bcd_descripcion_windows=Windows Server 2016 Datacenter
sistema3_variante2_bcd_uuid_hibernacion=30af8d3c-472d-11f0-a2e6-ba4d9717f5ae
sistema3_variante2_bcd_uuid_winre=e85c5247-4724-11f0-b2be-ff92e22e6019
sistema3_variante2_bcd_uuid_winre_boot-sdi=e85c5248-4724-11f0-b2be-ff92e22e6019

sistema3_variante2_inyectar_nombre_de_host=1

; Si quieres inyectar un unattend.xml, este es el sitio indicado. Se buscará dentro de la carpeta con el nombre de esta entrada de
; configuración (eso que está arriba entre corchetes), y evidentemente con el nombre que especifiques.
sistema3_variante2_inyectar_unattend-xml=0
sistema3_variante2_inyectar_unattend-xml_nombre_real=

; Si el equipo tiene un BIOS AMI y quieres inyectar una configuración / perfil de UEFI mediante SCEWIN, este es tu sitio.
; Decir que, aunque ya debes saber esto, meter un conjunto de variables en la NVRAM de "X" versión de ROM en un equipo ejecutando
; "Y" versión siempre sale mal. Los archivos van dentro de "
sistema3_variante2_inyectar_ajustes_de_UEFI=1
sistema3_variante2_inyectar_ajustes_de_UEFI_nombre_real_de_nvram-txt=nvram_f15c_sis3.txt

; =========================================================
; AVISO A NAVEGANTES. "ENABLEDELAYEDEXPANSION" esta acti-
; vado en el script "Colonizador.bat"; cualquier valor
; que contenga "!" o cualquier otro caracter utilizado por
; DELAYEDEXPANSION no aparecerá o romperá el script. Yo
; he avisado.
; =========================================================
